environment:
  nodejs_version: "6.3.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

  - npm run ci:eslint
  - npm run ci:compile

build: off
